### ISSUE TITLE
Cannot Start a New Book After Finishing a Book without Force Stopping the App

### ISSUE THREAD

**Issue by docsav** [PaulWoitaschek/Voice#676]
**App-Version:** 3.6.3
**Phone Name:** Blackberry Keyone BBB100-3
**Android Version:** 7.1.1

**Description of Problem**
After reaching the end of an audiobook (meaning the file is played to completion, then stops), I navigate in the app to the next book and press the play button. The button reacts as expected, performing the quick dim / rotation transition to the pause button. However, the file does not actually begin to play; the progress slider doesn't move and no sound is produced. Subsequent touches on the pause button produce the quick dim, but no transition back to the play icon. I have waited for about 10 minutes at one point, and the file does not begin to play in that time window. Stopping the app by closing it in the Recent Items view doesn't correct the problem. After force stopping the app in the settings menu, the book will play upon re-opening the app.

**Steps to Reproduce**
1. In Voice app, skip to the very last file of an audiobook
2.  Give the app ~30 seconds of playtime on the last file. Press play.
3. Lock the phone as the remainder of the book plays to completion (This may occur without the phone being locked, but when I was testing I didn't remember to test that variation.)
4. When the book is completed, unlock the phone and navigate to a new, un-played book in the Voice app.
5. Press the play button. Observe whether the file begins to play.
6. Attempt to press the pause button. It will not transition back to the play button.

**Desired Resolution**
Allow subsequent books to play after completing a book.

**Comment by duckpuppy** [comment]
I can confirm this behavior on different hardware:
**App-Version**: 3.6.3
**Phone Name**: Pixel 2
**Android Version**: 8.1

**Comment by Kamul-PL** [comment]
I've got the same issue. Anybody else?

BTW, there's another way to work around this problem. In my case it looks like that:
1. File A playback finished.
2. Second file (B) can't be played (because of Voice bug).
3. After that I chose third file (any other file than A and B). This one is played correctly.
4. Now it's possible to return to file B and this time it's played without any problems also.

**Comment by Usataroo** [comment]
Hi, I love this application!
I also have the same issue.

App-Version: 3.6.3
Phone Name: NEXUS 7  & Zenfone2
Android Version: 6.0.1 & 5.0

By the way of Kamul-PL,, I can play the second file.
Thanks a lot, Kamul-PL!
And I wish this bug is fixed formally.

**Comment by MagTun** [comment]
Kamul-PL solution didn't work for me. Here was my trick: let say you have just finish audiobook 1 and you want to listen to audiobook 2. Instead of going straight to audiobook 2, stay on audiobook 1, press play, wait one second, play pause, and then go to audiobook 2 and press play. By doing that, I no longer experienced the bug.

**Comment by Kamul-PL** [comment]
This is my second method to bypass the problem. I discovered it later and it seems I didn't share it here.:) I confirm this solution is even better.

**Comment by gwarser** [comment]
On 4.2.1 I still see small issue: after navigating to second book, "play" icon is in playback state (pause icon).

My STR:

- Voice in background
- first book finishes
- remove first book files/folders
- open Voice
- go back from first book and select second book from list
- "pause" icon visible on button, but I need to tap on it to start playback

**Comment by PaulWoitaschek** [comment]
With the 4.x versions this is fixed

@gwarser Can you open a new issue?
